title: "Leonard Mocanu - Software Craftsman"
description: ""
keywords:
  - software developer
  - oop
  - clean code
  - ddd
  - domain-driven design
  - php

author:
  name: "Leonard Mocanu"
  headline: "Software Craftsman (self-proclaimed)"
  bio: |
    Bucharest based <span>software developer</span>. Constantly experimenting with new technologies and techniques.
    I am very passionate about <span>Domain-Driven Design</span>, <span>Object-oriented analysis and design</span> and <span>Clean Code</span>.
  interests:
    - Domain-Driven Design
    - OOP
    - Clean Code
    - PHP

social_networks:
  twitter: "leonardmocanu2"
  github: "https://github.com/rattrap"
  email: "leonard@mocanu.me"
  url: ""